### ISSUE TITLE
Will html-validate be updated if one is found?

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata-htmlvalidation#1]
It seems to me it won't. How are html-validate updates handled though, what happens if a new version comes out?

**Comment by Piedone** [comment]
The author just updated the library with an important bugfix.

**Comment by YevgeniyShunevych** [comment]
No, it will not update automatically.

You can have the following code in global setup method:

```cs
new NpmCli().Install(HtmlValidateCli.Name, global: true);
// Executes: npm install -g html-validate
```

It will install the package if it is missing and also update the package if there is a newer version. But there is performance bottleneck, as this command takes several seconds to execute, about 8s on my machine.

Another option is to execute `npm install -g html-validate` script on CI pipeline as a step, as [here](https://github.com/atata-framework/atata-cli-htmlvalidate/blob/360b1a3da0192973da63ee28749aad591f6b5c12/azure-pipelines.yml#L47). And locally you can execute the same command manually.

Will any of these work for you?

**Comment by Piedone** [comment]
I see. Just running install all the time is not a good idea indeed.

However, we need something automated for updates because the issue is multiplied by all developers working on a given project and all other build environments. How about tieing Atata.HtmlValidation to a specific version of html-validate? This would be safer anyway since incompatibilities between versions make it risky to just install the latest html-validate version (a version Atata.HtmlValidation might not know about and be incompatible with).

Then this installation could happen just for the given version (`npm install -g html-validate@5.0.2-0`, for example). Before installation, you could run the quick `html-validate --version` command and the slow install would only happen if the returned version is lower or if html-validate is not installed at all.

**Comment by YevgeniyShunevych** [comment]
OK, this makes sense. I can add such method to `Atata.Cli.HtmlValidate` library:

```cs
new HtmlValidateCli()
    .RequireVersion("5.0.2", global: true);
```

**Comment by Piedone** [comment]
Sounds good! I wouldn't change anything in the higher-level APIs `ValidateHtml()` and `Validate()` though but I guess that's not necessary anyway.

**Comment by YevgeniyShunevych** [comment]
Yes, just like additional method that is not invoked in `HtmlValidator`, but can be invoked upon setup if needed, to ensure that needed version is installed.

**Comment by Piedone** [comment]
Would this be automatically invoked like the installation today? Because I think that would be the best (i.e. the consumer doesn't have to do anything special).

**Comment by YevgeniyShunevych** [comment]
@Piedone, I was thinking what we can do here. Here are my thoughts.

I can add a property `string RecommendedHtmlValidatePackageVersion { get; set; }` (defaults to `"5.x"`) to `HtmlValidationOptions`. So during HTML validation when "html-validate" package will not be found, then this `RecommendedHtmlValidatePackageVersion` version will install (currently, the latest installs). If any other version (for example 4.14.0
) is already installed on machine, then that installed version will be used.

When v6 of "html-validate" will appear, I can retest it. And if it will be compatible, `RecommendedHtmlValidatePackageVersion` can be incremented.

Anyway, if you want to stick to specific html-validate version, you'll be still able to invoke the following code upon global setup:

```cs
new HtmlValidateCli()
    .RequireVersion("5.1.0", global: true);
```

Or do the same using NPM script on CI:

```ps
npm install -g html-validate@5.1.0
```

What do you think @Piedone, should I add this `RecommendedHtmlValidatePackageVersion` property or maybe other ideas?

**Comment by Piedone** [comment]
While this looks good, we somehow need to cover updates too, I think `npm install` will just not do anything if the package is installed but has a different version and `npm update` needs to be run otherwise.

**Comment by YevgeniyShunevych** [comment]
Actually `npm install` replaces the current version with the specified version. You can test locally by executing such commands one after another:

```
npm install -g html-validate@5.1.0
npm install -g html-validate@4.14.0
```

**Comment by YevgeniyShunevych** [comment]
@Piedone, `RecommendedHtmlValidatePackageVersion` and `RequireVersion` features are implemented in the recently released [v1.1.0](https://github.com/atata-framework/atata-htmlvalidation/releases/tag/v1.1.0).

**Comment by Piedone** [comment]
With the updated version what do we have to do exactly if we want to use the latest 5.x version at any given time (i.e. 5.1.0 today, maybe 5.2.0 tomorrow)? Do I understand correctly that there's nothing needed as the default setup will already install (or update) that?

**Comment by YevgeniyShunevych** [comment]
Nope, `RecommendedHtmlValidatePackageVersion` will be installed only if there is no `html-validate` installed. Actually to be exact, [on error](https://github.com/atata-framework/atata-htmlvalidation/blob/main/src/Atata.HtmlValidation/HtmlValidator.cs#L176) when CLI command is executing. So it is only true for the first run on machine, then that version will be used for the next runs.

I thought you wanted to stick to specific version using the code like below:

```cs
new HtmlValidateCli()
    .RequireVersion("5.1.0", global: true);
```

Or just set this property with version needed:

```cs
RecommendedHtmlValidatePackageVersion = "5.1.0"
```

**Comment by YevgeniyShunevych** [comment]
@Piedone, can you please describe the versioning that you would like to have if the above is not what you need?

**Comment by Piedone** [comment]
My main goal, since with the NPM package we're talking about a dependency, is the ability to manage it safely and automatically, much like how it would happen if this NuGet would depend on another NuGet. So:

- Automatically use a version suitable for Atata.HtmlValidation. The suitable version should foremost be declared by Atata.HtmlValidation (with optionally be able to use a different one on your own peril).
- Automatically use the same version on every machine it's running on (i.e. the selected version is automatically installed if it's not already).
- If Atata.HtmlValidation updates to a new version then automatically update to it on every machine it's running on too.

So again, like it is with NuGet packages.

It seems to me that still an `html-validate --version` check before installation is the best option here.

**Comment by YevgeniyShunevych** [comment]
OK @Piedone, here is what I suggest:

- Replace `RecommendedHtmlValidatePackageVersion` options' property with `HtmlValidatePackageVersion` (set to `""5.1.1""`).
- In the beginning of `HtmlValidator.Validate` method execution add a check with installation of `html-validate` version with `new HtmlValidateCli().RequireVersion(_options.HtmlValidatePackageVersion)`.
 
By the way, `RequireVersion` executes `html-validate --version` under the hood.

**Comment by Piedone** [comment]
Looks good!

**Comment by YevgeniyShunevych** [comment]
@Piedone, v1.2.0 has been released with the above changes. Please check it out.

**Comment by Piedone** [comment]
So far looks good, thank you. Does anything need to be changed in the consumer code if it didn't use `RecommendedHtmlValidatePackageVersion` before?

**Comment by YevgeniyShunevych** [comment]
Great. No changes needed.

**Comment by Piedone** [comment]
Fantastic, thank you.
