### ISSUE TITLE
Ability to save formatted results to file later after validation

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata-htmlvalidation#2]
My use-case is that during UI test execution I'd like to take an `HtmlValidationResult` object and save it to a formatted file only later during execution, well after `Validate()` was run. This is necessary because `Validate()` is a step in the assertion of a test but a suitable folder to save such reports (and everything else useful for debugging the test) is only created at the end of test execution.

To achieve this now, I'd have to copy the relevant code from `Validate()`. I'd prefer not to do that and instead have a separate method to save a formatted HTML validation report.

**Comment by YevgeniyShunevych** [comment]
Why don't you just move the result and HTML files to the reports folder when it's known?

```cs
string artifactsDirectory = "..";

File.Move(htmlValidationResult.HtmlFilePath, Path.Combine(artifactsDirectory, "Html.html"));

if (htmlValidationResult.ResultFilePath != null)
    File.Move(htmlValidationResult.ResultFilePath, Path.Combine(artifactsDirectory, "HtmlValidationReport.txt"));
```

What do you think?

**Comment by Piedone** [comment]
Hmm, it would feel cleaner not to have to use files necessarily but this will be good for now, thanks.
