### ISSUE TITLE
Where is it recommended to run validation centrally?

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata-htmlvalidation#4]
I'd like to manage HTML validation in one place and automatically run it once a page loads in any case. This is for a project that utilizes Atata page classes only to a small extent. What would be your recommendation for this? There is no "page loaded" event in Selenium.

We do use central extension methods for clicking on elements and navigating to URLs (as in `RemoteWebDriver.Navigate()`). My idea is to extend these methods with automatic HTML validation if the URL changed after the action (or better, if a common element like `<html>` from before the action became stale after the action so even reloads of the same page will trigger it).

While clicks and explicit navigation are not necessarily the only actions that can change the HTML output of a page of course, nor is a crude dirty check like the URL changing or the `<html>` element becoming stale perfect but I think this is a good enough approach for most pieces of UI. Then for anything else not covered an explicit validation call can happen.

What do you think?

**Comment by YevgeniyShunevych** [comment]
Generally, I would probably execute HTML validation in a separate set of tests that only does the validation. Keeping functional E2E tests clean with only the verifications that they do. I prefer a concept of a test that does a single assertion, or a single joint set of assertions.

Invalid HTML, in case of injected HTML validation into regular UI tests, can fail and stop the test execution because of minor HTML issues. I would better have separate CI test results information, for functional UI tests and validation UI tests.

**Comment by YevgeniyShunevych** [comment]
If you surely want to inject HTML validation, then as an option is to create a trigger attribute like below:

```cs
public class ValidateHtmlAttribute : TriggerAttribute
{
    public ValidateHtmlAttribute(TriggerEvents on = TriggerEvents.Init, TriggerPriority priority = TriggerPriority.Medium)
        : base(on, priority)
    {
    }

    protected override void Execute<TOwner>(TriggerContext<TOwner> context)
    {
        context.Component.Owner.ValidateHtml();
    }
}
```

Then add it to all page classes to be invoked upon page object init:

```cs
AtataContext.GlobalConfiguration
    .Attributes.Global.Add(new ValidateHtmlAttribute());
```

Now this trigger will execute HTML validation at any page visit. But, as you mentioned, you firstly need to find a way to wait for a pages to load. There is no silver bullet here, you need to investigate client-side site engine to find an indicator of page readiness. It can be some HTML indicator or JavaScript flag/method. There are triggers in Atata, for example, for jQuery-based sites and Angular.js. Also, in case you are lucky to have good old non-SPA site, you can just do nothing as `Driver.Navigate().GoToUrl("...")` will wait for HTML page to be loaded.

**Comment by Piedone** [comment]
Great, thank you!

While in theory I'd agree that a test should have a single assertion but UI tests already do a lot of implicit assertions. And they're expensive so running them once is more than enough and I'd collect as much data as possible (an HTML validation error is a fail for the test regardless of it being logically correct).
