### ISSUE TITLE
"The directory name is invalid." exception

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata-htmlvalidation#5]
I get the following exception on the `Validate()` call:

```
Atata.Cli.CliCommandException: 'CLI command failure: cmd /c html-validate "08b61ee2-7371-4ad3-bb6a-6a5327873397.html" -f stylish
The directory name is invalid.'
```

There's no further information. I really have no idea what the problem might be. The test is not too different from others that work well. Also, there are multiple validation calls after each other that I think should all work in the same directory but just one fails consistently. However, I don't see why it would.

Do you happen to have any pointers on where to look?

**Comment by YevgeniyShunevych** [comment]
I didn't met such exception. Is there a stack trace?

**Comment by YevgeniyShunevych** [comment]
This exception can be thrown when you run the command with `WorkingDirectory` value referencing non-existent directory.

**Comment by Piedone** [comment]
The stack trace is of not much help and there's no further info at all, hence why I'm confused.

```
at Atata.Cli.CliCommand.Start()\r\n   at Atata.Cli.ProgramCli.Start(String arguments)\r\n   at Atata.Cli.ProgramCli.ExecuteRaw(String arguments)\r\n   at Atata.Cli.ProgramCli.Execute(String arguments)\r\n   at Atata.Cli.HtmlValidate.HtmlValidateCli.Validate(String path, HtmlValidateOptions options)\r\n   at Atata.HtmlValidation.HtmlValidator.<>c__DisplayClass14_0.<ExecuteCliCommand>b__0()\r\n   at Atata.LogManager.ExecuteSection[TResult](LogSection section, Func`1 function)\r\n   at Atata.HtmlValidation.HtmlValidator.ExecuteFunction[TResult](String sectionMessage, Func`1 function)\r\n   at Atata.HtmlValidation.HtmlValidator.ExecuteCliCommand(String workingDirectory, String htmlFileName, String formatter)\r\n   at Atata.HtmlValidation.HtmlValidator.Validate(String html)\r\n
```

I think it has to do something with path lengths though; if I move the whole project to a shorter path then it'll work. So, the usual Windows curse.

I'm not sure though, does this come from html-validate or Atata.Cli?

**Comment by YevgeniyShunevych** [comment]
Too long path was the second reason that I was thinking about.

It comes from .NET `System.Diagnostics.Process` class. I just wrap it with `CliCommandException` in `Atata.Cli.CliCommand` class. If you check the inner exception of that `CliCommandException` you can find:

```
 ---> System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Atata.Cli.CliCommand.Start() in D:\Development\atata-cli\src\Atata.Cli\CliCommand.cs:line 118
   --- End of inner exception stack trace ---
```
   
`Process.Start()` fails when `process.StartInfo.WorkingDirectory` has invalid path.

**Comment by Piedone** [comment]
Figured out that this happens if:
a) The HTML output file is written to the Atata artifacts folder (under a path along the lines of "test runtime directory\artifacts\2021-07-22 19_01_43\test name\48f9d45d-a929-443b-ae61-3e20f5212872.html"), and
b) the test's name is long, and
c) the validation fails.

However, a) is not always happening even if b) and c) does. I'm running all tests with the same config but still, sometimes a) happens, sometimes not.

I'll check if `LongPathsEnabled` helps.

**Comment by Piedone** [comment]
It doesn't. Also, the solution now is already in the drive root so can't really do anything with the path.

Since the artifacts folder is only used as a temp location in this case, couldn't we use a short hash of the test name instead?

**Comment by YevgeniyShunevych** [comment]
> Since the artifacts folder is only used as a temp location in this case, couldn't we use a short hash of the test name instead?

Absolutely. You can set `WorkingDirectory` property of `HtmlValidationOptions` to something different. For example, `WorkingDirectory = "htmlvalidation"` will put files of all tests into `...\bin\Debug\netcoreapp3.1\htmlvalidation` directory.

**Comment by Piedone** [comment]
Thank you, that does seem to do the trick. I guess the files won't clash even if all go into the same directory because they use GUIDs as their names?

**Comment by YevgeniyShunevych** [comment]
Correct. I primarily gave GUID names to files to allow using the same folder for tests.

**Comment by Piedone** [comment]
Great, this will work then.
