### ISSUE TITLE
Update html-validate to 5.2.0

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata-htmlvalidation#6]
`HtmlValidatePackageVersion` works perfectly and I can select to use v5.2.0 of html-validate. Nevertheless, at one point please update the default version too.

**Comment by YevgeniyShunevych** [comment]
Great! I've just updated it and released v1.4.0.

**Comment by Piedone** [comment]
Thank you!

**Comment by YevgeniyShunevych** [comment]
You are welcome.
